FROM node:18.18-alpine3.18
LABEL maintainer="Manticore Software Co. Ltd <contact@manticoresearch.com>"

RUN mkdir -p /src
COPY app/client/package.json /src
ENV BUILD_DEPS="build-base python3"
RUN apk add $BUILD_DEPS && \
  cd /src && npm install && npm cache --force clean && \
  apk del $BUILD_DEPS
COPY app/client/. /src/

WORKDIR /src
