php: -t ${COMPOSE_PROJECT_NAME}/php:${REVISION}
nginx: -t ${COMPOSE_PROJECT_NAME}/nginx:${REVISION}
webpack: -t ${COMPOSE_PROJECT_NAME}/webpack:${REVISION}
queue: -t ${COMPOSE_PROJECT_NAME}/queue:1.11-a
