#!/usr/bin/env /src/bin/php-exec
<?php declare(strict_types=1);

use App\Component\Search;
use App\Lib\Queue;
use App\Model\Org;
use App\Model\Repo;

$hostname = gethostname();
$no = (int)ltrim(substr($hostname, -2), '.');
$tokens = array_map('trim', explode(' ', getenv("GITHUB_TOKENS") ?: ''));
if (!isset($tokens[$no])) {
	Cli::error("Missing token in GITHUB_TOKENS with no #{$no}");
}
putenv('GITHUB_TOKEN=' . $tokens[$no]);

$ns = 'github-issue-fetch';
Cli::print("Queue NS: $ns");

Queue::process($ns, function (array $job) {
	/** @var Org $org */
	/** @var Repo $repo */
	[$org, $repo] = $job;
	Cli::print("Indexing #{$repo->id}: https://github.com/{$org->name}/{$repo->name}");
	Search::index($org, $repo);
	Queue::add('notification-send', [$org, $repo]);
	Cli::print(' done');
	return true;
});
