#!/usr/bin/env /src/bin/php-exec
<?php declare(strict_types=1);

use App\Component\Search;
use App\Lib\Queue;
use App\Model\Repo;

$hostname = gethostname();
$no = (int)ltrim(substr($hostname, -2), '.');
putenv('GITHUB_TOKEN=' . getenv("GITHUB_TOKEN_{$no}"));

$ns = 'github-issue-fetch';
Cli::print("Queue NS: $ns");

Queue::process($ns, function (Repo $repo) {
	Cli::print("Indexing #{$repo->id}: https://github.com/{$repo->org}/{$repo->name}");
	Search::index($repo);
	Queue::add('notification-send', $repo);
	Cli::print(' done');
	return true;
});
